services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-app-stack
    ports:
      - "8080:8080"
    volumes:
      - ./webapp:/var/www/html
    networks:
      - ci4-app-stack-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ci4-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: cipassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - ci4-app-stack-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4-app-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - ci4-app-stack-network
    depends_on:
      - db

networks:
  ci4-app-stack-network:
    driver: bridge
